from __future__ import annotations

PROVIDER_REQUEST_TIMEOUT = 30.0

DEFAULT_DISCOVERY_CACHE_SECONDS = 600.0

DISCOVERY_CACHE_SECONDS_ENV = "BEEHAIIVE_GITHUB_DISCOVERY_CACHE_SECONDS"

SECONDARY_RATE_LIMIT_FALLBACK_SECONDS = 60.0

HANDOFF_RATE_LIMIT_RETRIES = 2

__all__ = [
    "PROVIDER_REQUEST_TIMEOUT",
    "DEFAULT_DISCOVERY_CACHE_SECONDS",
    "DISCOVERY_CACHE_SECONDS_ENV",
    "SECONDARY_RATE_LIMIT_FALLBACK_SECONDS",
    "HANDOFF_RATE_LIMIT_RETRIES",
]
