from __future__ import annotations

MAX_PBI_RELATION_CHILDREN = 20

MAX_PBI_RELATION_DEPENDENCIES = 100

MAX_PBI_RELATION_GRAPH_ISSUES = 500

__all__ = [
    "MAX_PBI_RELATION_CHILDREN",
    "MAX_PBI_RELATION_DEPENDENCIES",
    "MAX_PBI_RELATION_GRAPH_ISSUES",
]
