from __future__ import annotations

SCHEDULER_ENABLED_ENV = "BEEHAIIVE_SCHEDULER_ENABLED"
SCHEDULER_POLL_INTERVAL_ENV = "BEEHAIIVE_SCHEDULER_POLL_INTERVAL_SECONDS"
SCHEDULER_MAX_CONCURRENCY_ENV = "BEEHAIIVE_SCHEDULER_MAX_CONCURRENCY"
DEFAULT_SCHEDULER_POLL_INTERVAL_SECONDS = 600.0
DEFAULT_SCHEDULER_MAX_CONCURRENCY = 1
SCHEDULER_SHUTDOWN_TIMEOUT_SECONDS = 30.0

__all__ = [
    "DEFAULT_SCHEDULER_MAX_CONCURRENCY",
    "DEFAULT_SCHEDULER_POLL_INTERVAL_SECONDS",
    "SCHEDULER_ENABLED_ENV",
    "SCHEDULER_MAX_CONCURRENCY_ENV",
    "SCHEDULER_POLL_INTERVAL_ENV",
    "SCHEDULER_SHUTDOWN_TIMEOUT_SECONDS",
]
